services:
  app:
    build: .
    env_file:
      - env/.env.app
    depends_on:
      - db
      - redis
    develop:
      watch:
        - action: sync+restart
          path: ./dist
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  db:
    image: mariadb
    env_file:
      - env/.env.db
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis
    env_file:
      - env/.env.redis
    volumes:
      - type: volume
        source: redis-data
        target: /data
      - type: bind
        source: ./env/redis.conf
        target: /etc/redis/redis.conf
volumes:
  db-data:
  redis-data:
