name: ci

on:
  push:
    branches: master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        timeout-minutes: 5 
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        timeout-minutes: 5
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        timeout-minutes: 1
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: akatukisora/test-ripository:latest
        timeout-minutes: 10
            